//
// Created by ilia on 17.09.23.
//

#ifndef OPTIMIZATION_COURSE_ASSIGNMENT_1_SIMPLEXMETHOD_HPP
#define OPTIMIZATION_COURSE_ASSIGNMENT_1_SIMPLEXMETHOD_HPP


class SimplexMethod {

};


#endif //OPTIMIZATION_COURSE_ASSIGNMENT_1_SIMPLEXMETHOD_HPP
